### PR TITLE
Added `js-borschik-include` tech

### LINKED ISSUE #10: Add `borschik-include` tech
If in source code use `borschik:include` then to correctly replace by the file's content need build target which is `borschik:include` and use `borschik` tech.

Expected target result for `js-borschik-include` tech:

```js
/*borschik:include:./path/to/file-1.js*/
/*borschik:include:./path/to/file-2.js*/
/* ... */
```

Reed more about `borschik:include` in the [docs](https://github.com/bem/borschik/blob/master/docs/js-include/js-include.en.md).

### PR DESCRIPTION
**Pull request by andrewblond**
Resolved #10

### CODE REVIEW

**Comment by voischev** [comment]
:+1:! Очень надо

**Comment by teryaem** [comment]
+1

**Comment by mdevils** [comment]
Thank you for your contribution!

**Comment by mdevils** [comment]
Released in `enb-borschik@1.5.0`

**Pull request merged**
