### PR TITLE
Add deps targets option to borschik technology

### LINKED ISSUE #24: Add dependencies option to borschik technology
We need to add .useSourceListFilenames('depsTargets') to borschik technology.
It needs to control order of targets builds.
css and js files must be ready before borschik execution

### PR DESCRIPTION
**Pull request by tormozz48**
Resolved #24 

@blond @sipayRT @tavriaforever 
Please review it.

P.S. @aliosv It is a part of your https://github.com/enb-make/enb-borschik/pull/12.

We already have rewritten borschik technology to build-flow base.
This pr should fix problem enb-make/enb#219

Please send your opinion about this

### CODE REVIEW

**Comment by sipayRT** [comment]
what about tests?

**Comment by tormozz48** [comment]
> what about tests?

It is build-flow functionality.

**Comment by blond** [comment]
The use of `target` word to indicate source files may introduce user confusion.

I suggest to use `dependantFiles` option name instead of `depsTargets`.

**Comment by blond** [comment]
@tormozz48 squash commits, please.

**Comment by blond** [comment]
@tormozz48 and add docs to README.md

**Pull request merged**
